export const categories = [
  {
    id: 1,
    name: "Ones",
    description: "Sum of all ones",
    score: 0,
    isFilled: false,
  },
  {
    id: 2,
    name: "Twos",
    description: "Sum of all twos",
    score: 0,
    isFilled: false,
  },
  {
    id: 3,
    name: "Threes",
    description: "Sum of all threes",
    score: 0,
    isFilled: false,
  },
  {
    id: 4,
    name: "Fours",
    description: "Sum of all fours",
    score: 0,
    isFilled: false,
  },
  {
    id: 5,
    name: "Fives",
    description: "Sum of all fives",
    score: 0,
    isFilled: false,
  },
  {
    id: 6,
    name: "Sixes",
    description: "Sum of all sixes",
    score: 0,
    isFilled: false,
  },
  {
    id: 7,
    name: "Sum",
    description: "Sum of all dices",
    score: 0,
    isFilled: false,
  },
  {
    id: 8,
    name: "Bonus",
    description: "Bonus if sum is greater than 63",
    score: 0,
    isFilled: false,
  },
  {
    id: 9,
    name: "One pair",
    description: "Sum of two highest dices",
    score: 0,
    isFilled: false,
  },
  {
    id: 10,
    name: "Two pairs",
    description: "Sum of two highest pairs",
    score: 0,
    isFilled: false,
  },
  {
    id: 11,
    name: "Three of a kind",
    description: "Sum of three highest dices",
    score: 0,
    isFilled: false,
  },
  {
    id: 12,
    name: "Four of a kind",
    description: "Sum of four highest dices",
    score: 0,
    isFilled: false,
  },
  {
    id: 13,
    name: "Small straight",
    description: "Sum of all dices if 1,2,3,4,5",
    score: 0,
    isFilled: false,
  },
  {
    id: 14,
    name: "Large straight",
    description: "Sum of all dices if 2,3,4,5,6",
    score: 0,
    isFilled: false,
  },
  {
    id: 15,
    name: "Full house",
    description: "Sum of all dices if 3 of a kind and a pair",
    score: 0,
    isFilled: false,
  },
  {
    id: 16,
    name: "Chance",
    description: "Sum of all dices",
    score: 0,
    isFilled: false,
  },
  {
    id: 17,
    name: "Yamb",
    description: "Sum of all dices if all are the same",
    score: 0,
    isFilled: false,
  },
  {
    id: 18,
    name: "Total",
    description: "Sum of all scores",
    score: 0,
    isFilled: false,
  },
];
